export const edificios = [
  'Casa Navarro',
  'Ed. Fernando Barón',
  'Ed. Gabriel Giraldo',
  'Ed. Gerardo Arango Puerta',
  'Talleres de Diseño Industrial',
  'Ed. Lorenzo Uribe',
  'Ed. Ático',
  'Ed. Julio Carrizosa',
  'Ed. José Gabriel Maldonado',
  'Ed. Luis Felipe Silva Garativo',
  'Ed. Leopoldo Rother',
  'Ed. Carlos Arbeláez Camacho',
  'Capilla Nuestra Señora del Camino',
  'Talleres de Arquitectura',
  'Ed. Jorge Hoyos Vásquez',
  'Ed. Emilio Arango',
  'Cafetería Central',
  'Hospital Universitario San Ignacio',
  'Facultad de Educación',
  'Facultad de Odontología',
  'Ed. José del Carmen Acosta',
  'Ed. Jesús María Fernandez',
  'Urgencias HUSI',
  'Ed. Néstor Santacoloma',
  'Ed. Rafael Barrientos Conto',
  'Instituto de Genética Humana',
  'Auditorio Alejandro Novoa',
  'Central de Vigilancia',
  'Ed. Pavlo VI',
  'Facultad de Artes Ala Oriental',
  'Ed. Catalán',
  'Salones Carrera de Estudios Musicales',
  'Capilla San Francisco Javier',
  'Ed. Cataluña',
  'Ed. Quindío',
  'Ed. Juniorado, Bienestar',
  'Auditorio Félix Restrepo',
  'Ed. Ángel Valtierra',
  'Ed. Carlos Ortiz',
  'Ed. Jesús Emilio Ramírez',
  'Ed. Bioterio',
  'Ed. José Rafael Arboleda',
  'Cancha de Fútbol',
  'Centro Javeriano de Formación Deportiva',
  'Ed. Pedro Arrupe',
  'Ed. Manuel Briceño Jáuregui',
  'Ed. Don Guillermo Castro',
  'Ed. Hernando Arellano Ángel'
]
